server:
  port: 8088


spring:
  application:
    name: goshop
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/goshop?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1234
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 20
  #redis配置
  redis:
    host: 127.0.0.1 #Redis服务器地址
    port: 6379  #Redis服务器连接端口
    database: 0 #Redis数据库索引（默认为0）
    timeout: 5000ms #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 50  #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20  #连接池中的最大空闲连接
        min-idle: 2 #连接池中的最小空闲连接
  #kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1
    consumer:
      group-id: consumerGroup
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000
    listener:
      ack-mode: manual_immediate #手动调用Acknowledgment.acknowledge()后立即提交


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sh.goshop.entity



############# 业务配置 #############

jxm:
  name: songhuihui

kafka:
  topic:
    topicOne: notice_topic_1
    topicTwo: notice_topic_2