server:
  port: 8088

#redis配置
spring:
  redis:
    host: 127.0.0.1 #Redis服务器地址
    port: 6379  #Redis服务器连接端口
    database: 0 #Redis数据库索引（默认为0）
    timeout: 5000ms #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 50  #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20  #连接池中的最大空闲连接
        min-idle: 2 #连接池中的最小空闲连接
  application:
    name: goshop

jxm:
  name: songhuihui